import { mkdirSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { join } from "node:path";
import { REGISTRY_URL } from "../constants.js";

export function scaffoldPackage(
    name: string,
    version: string,
    wrapperContent: string,
    cwd: string = process.cwd(),
): void {
    const pkgDir = join(cwd, "node_modules", name);
    
    if (existsSync(pkgDir)) {
        rmSync(pkgDir, { recursive: true, force: true });
    }

    mkdirSync(pkgDir, { recursive: true });

    const pkgJson = {
        name: name,
        version: version,
        main: "./index.js",
        type: "module",
        _mlnpm: true,
    };

    writeFileSync(
        join(pkgDir, "package.json"),
        JSON.stringify(pkgJson, null, 2) + "\n",
    );

    const indexJs = `// Auto-generated by mlnpm CLI — do not edit manually
import { createModel } from "@mlnpm/runtime";
import wrapperConfig from "./wrapper.config.js";
const model = createModel({
    ...wrapperConfig,
    name: ${JSON.stringify(name)},
    version: ${JSON.stringify(version)},
    registryUrl: ${JSON.stringify(REGISTRY_URL)},
});
export default model;
`;

    writeFileSync(join(pkgDir, "index.js"), indexJs);
    writeFileSync(join(pkgDir, "wrapper.config.js"), wrapperContent);
}

export function removePackage(
    name: string,
    cwd: string = process.cwd(),
): void {
    const pkgDir = join(cwd, "node_modules", name);
    if (existsSync(pkgDir)) {
        rmSync(pkgDir, { recursive: true, force: true });
    }
}

export function isInstalled(
    name: string,
    cwd: string = process.cwd(),
): boolean {
    const pkgDir = join(cwd, "node_modules", name);
    return existsSync(join(pkgDir, "package.json"));
}